services:
  - type: web
    name: myth-weaver
    env: node
    plan: free
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ..
      npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
